### ISSUE TITLE
Unexpected problem

### ISSUE THREAD

**Issue by ddehita** [seashore001x/Rrumen#1]
Hello! I'm very new at bioinformatics and I'm trying to analyze my data by LEfSe. I found your script for converting phyloseq objects to lefse tables. It is wonderful for me, but... it doesn't work when I applied the function.

The error message is: Error in grouped_df_impl(data, unname(vars), drop) : 
  Column `Kingdom` is unknown

My tax_table doesn't have Kingdom taxa, instead, it is called Rank1... I tried to change the word Kingdom in your function by Rank1, but it doesn't work... Also, I tried to eliminate the Kingdom word, but it also didn't work.

Thanks in advance for your help, and thank you for creating this useful tool.

**Comment by seashore001x** [comment]
Change the header of your phyloseq table into Kingdom, Phylum, Class, Order, Family, Genus .
