### ISSUE TITLE
Problem loading quite output as a phyloseq object

### ISSUE THREAD

**Issue by adrianmu** [seashore001x/Rrumen#2]
I have problems loading the OTU table and Taxa. i am under the impression the OTU table is the output after the denoising step, however the taxa is generated from the representative.sequences.qza file. So when try to merge these two outputs into a phyloseq object i get an error that taxa/otu do not macth could someone help 

Error in validObject(.Object) : invalid class “phyloseq” object: 
 Component taxa/OTU names do not match.
 Taxa indices are critical to analysis.
 Try taxa_names()

**Comment by seashore001x** [comment]
Please make sure row names matched exactly.
